apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.servicename }}
  labels:
    app: {{ .Values.servicename }}
    tier: backend
spec:
  ports:
  - protocol: TCP
    port: {{ .Values.servicePort }}
    targetPort: {{ .Values.servicePort }}
  type: ClusterIP
  selector:
    app: {{ .Values.servicename }}
