{{- if .Values.credentials }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-info
  namespace: {{ .Values.namespace }}
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  db.json  : {{.Values.credentials | toJson | b64enc }}
{{- end }}