{{- if .Values.oauthCredentials }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-oauth
  namespace: {{ .Values.namespace }}
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  IDP_CLIENT_SECRET  : {{.Values.oauthCredentials.IDP_CLIENT_SECRET | b64enc}}
{{- end }}