apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.servicename }}
  namespace: '{{ .Release.Namespace }}'
  labels:
    app.kubernetes.io/name: {{ .Values.servicename }}
    tier: backend
spec:
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.servicePort }}
    targetPort: {{ .Values.servicePort }}
  - name: metrics
    protocol: TCP
    port: {{ .Values.metricsPort }}
    targetPort: {{ .Values.metricsPort }}
  type: ClusterIP
  selector:
    app: {{ .Values.servicename }}
