# Default values for configserver-chart.
# This is a YAML-formatted file.
#
# This file provides project specific variables and is joined with another value file
# in MasterDeployments or MinikubeDeployment repos.
#
# When helm is launched it will be done so like this:
#
#  helm template -f <valuesfile> <chartlocation>  > outputfile
#
# and the output will be redirected to a yaml file which will then be manually kubectl applied

# local variables for this deployment can go here

ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    cert-manager.io/cluster-issuer: letsencrypt

dimage: go-template
microk8s: false
replicas: 1
servicename: nyota-go-template
servicePort: 5000
