#%RAML 1.0
title: Location service REST  API
version: v1
protocols: [ HTTPS ] 
baseUri: https://<localhost>/api/{version}
mediaType: application/json

/deviceZone:
  description: "This is used to get device zone"
  get:
    queryParameters:
      deviceId:
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "data": {
                    "zone": "",
                  },
                  "success": true,
                  "status": 200
                }

