---
# Source: go-template/templates/deploy.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: go-template-configmap
  namespace: default
data:
  BACKEND_TYPE: "local_something"
---
# Source: go-template/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nyota-rest-go-template
  labels:
    app: nyota-rest-go-template
    tier: backend
spec:
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP
  selector:
    app: nyota-rest-go-template
---
# Source: go-template/templates/deploy.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nyota-rest-go-template
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nyota-rest-go-template
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
        prometheus.io/path: /metrics
    spec:
      containers:
      - name: nyota-rest-go-template
        image: "frontlinedev.azurecr.io/microservices/nyota-rest-go-template:46"
        ports:
        - containerPort: 5000
        envFrom:
          - configMapRef:
              name: go-template-configmap
      nodeSelector:
        agentpool: "default"
