{
 "title": "Hello World App",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(node_cpu_seconds_total, cluster)"
    }
   },
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Hello App Metrics Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Promhttp Metric Handler Requests Total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "promhttp_metric_handler_requests_total{job='sre-go-helloworld', cluster=~\"$cluster\"}",
     "legendFormat": "http-code-{{code}}"
    }
   ]
  },
  {
   "title": "http response size bytes sum Code 200",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(http_response_size_bytes_sum{job='sre-go-helloworld', cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Promhttp Metric Handler Requests Total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(promhttp_metric_handler_requests_total{job='sre-go-helloworld', cluster=~\"$cluster\"}[$interval])"
    },
    {}
   ]
  },
  {
   "title": "DB Open Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gorm_dbstats_open_connections{job='sre-go-helloworld', cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Http Request Duration Seconds code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum{job='sre-go-helloworld', cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Http Requests Inflight",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_requests_inflight{job='sre-go-helloworld', cluster=~\"$cluster\"}"
    }
   ]
  },
  { "title": "Go App Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Process Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job='sre-go-helloworld', cluster=~\"$cluster\"}"
    },
    {
     "expr": "process_virtual_memory_bytes{job='sre-go-helloworld', cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Process Memory Deriv",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(process_resident_memory_bytes{job='sre-go-helloworld', cluster=~\"$cluster\"}[$interval])"
    },
    {
     "expr": "deriv(process_virtual_memory_bytes{job='sre-go-helloworld', cluster=~\"$cluster\"}[$interval])"
    }
   ]
  },
  {
   "title": "Go Memstats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes{job='sre-go-helloworld', cluster=~\"$cluster\"}[$interval])"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job='sre-go-helloworld', cluster=~\"$cluster\"}[$interval])"
    },
    {
     "expr": "rate(go_memstats_stack_inuse_bytes{job='sre-go-helloworld', cluster=~\"$cluster\"}[$interval])"
    },
    {
     "expr": "rate(go_memstats_heap_inuse_bytes{job='sre-go-helloworld', cluster=~\"$cluster\"}[$interval])",
     "legendFormat": "{{pod}} - heap inuse"
    }
   ]
  },
  {
   "title": "Go Memstats Deriv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "deriv(go_memstats_alloc_bytes{job='sre-go-helloworld', cluster=~\"$cluster\"}[$interval])"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job='sre-go-helloworld', cluster=~\"$cluster\"}[$interval])"
    },
    {
     "expr": "deriv(go_memstats_stack_inuse_bytes{job='sre-go-helloworld', cluster=~\"$cluster\"}[$interval])"
    },
    {
     "expr": "deriv(go_memstats_heap_inuse_bytes{job='sre-go-helloworld', cluster=~\"$cluster\"}[$interval])",
     "legendFormat": "{{pod}} - heap inuse"
    }
   ]
  },
  {
   "title": "Open Fds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_open_fds{job='sre-go-helloworld', cluster=~\"$cluster\"}[$interval])"
    }
   ]
  },
  {
   "title": "Open Fds Deriv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deriv(process_open_fds{job='sre-go-helloworld', cluster=~\"$cluster\"}[$interval])"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_goroutines{job='sre-go-helloworld', cluster=~\"$cluster\"}[$interval])"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_sum{job='sre-go-helloworld', cluster=~\"$cluster\"}[$interval])"
    }
   ]
  }
 ]
}