apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: {{ .Values.namespace }}
  metadata:
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}