apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Values.namespace }}
data:
  IDP_LABEL: "okta"
  IDP_CLIENT_ID: "OIDC_CLIENT_ID"
  IDP_ISSUER: "https://OIDC_ISSUSER_URL"
  IDP_AUDIENCE: "api://helloworld"
  IDP_LOGIN_CALLBACK: "https://helloworld.{{ .Values.domainName }}/auth/login/token"
  IDP_ISSUER_LOGOUT_PATH : "/v1/logout"
