apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: "{{ .Release.Name }}-secrets"
  namespace: {{ .Values.namespace }}
spec:

  # SecretStoreRef defines which SecretStore to use when fetching the secret data
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: {{ .Values.externalSecrets.secretStoreKind }}  # or SecretStore

  # RefreshInterval is the amount of time before the values reading again from the SecretStore provider
  # Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h" (from time.ParseDuration)
  # May be set to zero to fetch and create it once
  refreshInterval: "1h"

  # the target describes the secret that shall be created
  # there can only be one target per ExternalSecret
  target:

    # The secret name of the resource
    # Defaults to .metadata.name of the ExternalSecret
    # It is immutable
    name: "{{ .Release.Name }}-secrets"

    # Enum with values: 'Owner', 'Merge', or 'None'
    # Default value of 'Owner'
    # Owner creates the secret and sets .metadata.ownerReferences of the resource
    # Merge does not create the secret, but merges in the data fields to the secret
    # None does not create a secret (future use with injector)
    creationPolicy: 'Merge'

  # Data defines the connection between the Kubernetes Secret keys and the Provider data
  data:
    {{- range .Values.externalSecrets.data }}
    - {{ . | toYaml | nindent 6 }}
    {{- end }}