# Default values for configserver-chart.
# This is a YAML-formatted file.
#
# This file provides project specific variables and is joined with another value file
# in MasterDeployments or MinikubeDeployment repos.
#
# When helm is launched it will be done so like this:
#
#  helm template -f <valuesfile> <chartlocation>  > outputfile
#
# and the output will be redirected to a yaml file which will then be manually kubectl applied

# local variables for this deployment can go here

ingress:
  apiVersion: networking.k8s.io/v1beta1
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-staging

dockerPreamable: 626007623524.dkr.ecr.us-east-2.amazonaws.com
domainPrefix: helloworld-go
servicePort: "5000"
metricsPort: "5001"
dbname: helloworlddev

oidc_client_id: SET_IN_DEPLOYMENT_REPO
oidc_issuer_url: SET_IN_DEPLOYMENT_REPO

# Environment-specific values
namespace: SET_IN_DEPLOYMENT_REPO       # Overridden in deployment repo for env-specific namespace
tagversion: SET_IN_DEPLOYMENT_REPO      # Defer to deployment repo to capture appropriate version for target environment
dimage: SET_IN_DEPLOYMENT_REPO          # Defer to deployment repo to capture appropriate image name for dev/staging/prod
domainName: SET_IN_DEPLOYMENT_REPO      # Defer to deployment repo to capture appropriate domain name for dev/staging/prod
replicas: 1                             # Default replica count; override in deployment repo for env-specific replica count
deploymentEnv: SET_IN_SRE_CLUSTER_CONFIG_REPO # Defer to sre_cluster_config repo; Value of this param should not impact application

existingEnvSecret:
