apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.dimage }}
  labels:
    app: {{ .Values.dimage }}
    tier: backend
spec:
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP
  selector:
    app: {{ .Values.dimage }}
