{
 "title": "Hello World App",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Source", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(go_memstats_alloc_bytes{job=~\"$job\"}, namespace)"
   },
   {
    "name": "pod",
    "query": "label_values(process_resident_memory_bytes{job=~\"$job\"}, pod)"
   },
   { "name": "interval", "query": "1m,5m,10m,30m,1h" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(http_requests_request_duration, job)"
   },
   {
    "name": "Method",
    "label": "Method",
    "query": "label_values(http_requests_request_duration{job=~\"$job\"}, method)"
   },
   {
    "name": "Endpoint",
    "label": "Endpoint",
    "query": "label_values(http_requests_request_duration{job=~\"$job\"}, endpoint)"
   },
   {
    "name": "app",
    "query": "label_values(process_resident_memory_bytes{app=~\"$app\"}, app)"
   }
  ]
 },
 "panels": [
  { "title": "Hello App Metrics Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Promhttp Metric Handler Requests Total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "promhttp_metric_handler_requests_total{job=\"sre-go-helloworld\"}",
     "legendFormat": "http-code-{{code}}"
    }
   ]
  },
  {
   "title": "http response size bytes sum Code 200",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "http_response_size_bytes_sum{job=\"sre-go-helloworld\", code=\"200\"}"
    }
   ]
  },
  {
   "title": "Promhttp Metric Handler Requests Total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(prometheus_http_request_duration_seconds_count)"
    }
   ]
  },
  {
   "title": "DB Open Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gorm_dbstats_open_connections{job=\"sre-go-helloworld\", db_name=\"helloworld\"}"
    }
   ]
  },
  {
   "title": "Http Request Duration Seconds code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum"
    }
   ]
  },
  {
   "title": "Http Requests Inflight",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "http_requests_inflight" }
   ]
  },
  { "title": "Go App Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Process Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes" },
    { "expr": "process_virtual_memory_bytes" }
   ]
  },
  {
   "title": "Process Memory Deriv",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(process_resident_memory_bytes[$interval])"
    },
    {
     "expr": "deriv(process_virtual_memory_bytes[$interval])"
    }
   ]
  },
  {
   "title": "Go Memstats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "go_memstats_alloc_bytes" },
    {
     "expr": "rate(go_memstats_alloc_bytes_total[30s])"
    },
    { "expr": "go_memstats_stack_inuse_bytes" },
    {
     "expr": "go_memstats_heap_inuse_bytes{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\",job=~\"$job\"}",
     "legendFormat": "{{pod}} - heap inuse"
    }
   ]
  },
  {
   "title": "Go Memstats Deriv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "deriv(go_memstats_alloc_bytes[$interval])"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total[$interval])"
    },
    {
     "expr": "deriv(go_memstats_stack_inuse_bytes[$interval])"
    },
    {
     "expr": "deriv(go_memstats_heap_inuse_bytes{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\",job=~\"$job\"}[$interval])",
     "legendFormat": "{{pod}} - heap inuse"
    }
   ]
  },
  {
   "title": "Open Fds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_open_fds" }
   ]
  },
  {
   "title": "Open Fds Deriv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deriv(process_open_fds[$interval])"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_goroutines" }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "go_gc_duration_seconds_sum" }
   ]
  }
 ]
}