basePath: /v1
definitions:
  models.APIResponse:
    properties:
      code:
        type: integer
      data:
        type: object
      desc:
        type: string
      errors:
        items:
          $ref: '#/definitions/models.Error'
        type: array
      links:
        $ref: '#/definitions/models.Links'
        type: object
    type: object
  models.Error:
    properties:
      code:
        type: integer
      error:
        type: string
      field:
        type: string
    type: object
  models.Links:
    properties:
      first:
        type: string
      last:
        type: string
      next:
        type: string
      prev:
        type: string
    type: object
info:
  contact: {}
  license:
    name: Apache 2.0
  termsOfService: http://swagger.io/terms/
  title: Template API
  version: "1.0"
paths:
  /:
    get:
      consumes:
        - application/json
      description: get a response from home endpoint
      operationId: get-home
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.APIResponse'
      summary: Get Home
      tags:
        - Home
  /deviceZone/{deviceId}:
    get:
      consumes:
        - application/json
      description: get device zone by device Id
      operationId: get-device-zone
      parameters:
        - description: Device ID
          in: path
          name: deviceId
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.APIResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.APIResponse'
      summary: Get Device Zone
      tags:
        - DeviceZone
swagger: "2.0"
