{{- if  .Values.namespace }}
apiVersion: v1
kind: Namespace
metadata:
{{- if  .Values.namespace }}
  name: {{ .Values.namespace }}
{{- else }}
  name: sre-go-sre-go-helloworld.git.git
{{- end }}
{{- end }}