{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sre-go-sre-go-helloworld.git.git-app.serviceAccountName" . }}
  labels:
    {{- include "sre-go-sre-go-helloworld.git.git-app.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}